global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
# - job_name: otel
#   static_configs:
#   - targets:
#     - 'otelcol:9464'
# - job_name: otel-collector
#   static_configs:
#   - targets:
#     - 'otelcol:8888'
# We could also just do a remote-write
- job_name: fluent-bit
  static_configs:
  - targets:
    - 'otelcol:2021'
